### ISSUE TITLE
anki-mode-connect gets null data

### ISSUE THREAD

**Issue by sboisen** [davidshepherd7/anki-mode#2]
When i invoke anki-mode i get this message: `anki-mode-connect got null data` ...

I've confirmed in the browser that AnkiConnect is running locally on http://localhost:8765/. 

When i try completion on the "Choose deck:" command, there aren't any decks, which supports the hypothesis that it can't connect to AnkiConnect. 

Any suggestions for how to diagnose this further?

**Comment by davidshepherd7** [comment]
It's probably because I'm using version 2 of AnkiConnect but it's up to version 5 (!) now. Try this patch to request version 2 of the api:

```
index d6ddadd..0e2d2a1 100644
--- a/anki-mode.el
+++ b/anki-mode.el
@@ -124,7 +124,7 @@ to default to the one used by markdown mode if it is set."
 (defun anki-mode-connect (callback method params sync)
   (request "http://localhost:8765"
            :type "POST"
-           :data (json-encode `(("action" . ,method) ("params" . ,params)))
+           :data (json-encode `(("action" . ,method) ("params" . ,params) ("version" . anki-mode--required-anki-connect-version)))
            :headers '(("Content-Type" . "application/json"))
            :parser 'json-read
            :sync sync
```

I won't push it yet because I don't really have time to check it properly at the moment.

**Comment by davidshepherd7** [comment]
@sboisen Did that patch help?

**Comment by davidshepherd7** [comment]
This should be fixed in the latest version.
